### ISSUE TITLE
Quiz issue

### ISSUE THREAD

**Issue by RubaMM** [zero-nnkn/video-quiz-generator#4]
when i just use it from docker it is work but tle quiz generate dose not work .

**Comment by zero-nnkn** [comment]
@RubaMM , can you describe the bug and how to reproduce it?

**Comment by RubaMM** [comment]
there is no bug and the website work but when I click on generate to generate the quiz it dose not generate the quiz .

**Comment by zero-nnkn** [comment]
Which API key did you use? Bard or OpenAI GPT?

**Comment by RubaMM** [comment]
I used OpenAI GPT

**Comment by RubaMM** [comment]
did you now what the problem?

**Comment by zero-nnkn** [comment]
There is a bug in calling the API, I will fix it.

**Comment by RubaMM** [comment]
can you notice me if you fix it?

**Comment by zero-nnkn** [comment]
Hi @RubaMM,
The issue was fixed in #5.
You can go ahead and test it now.
